### ISSUE TITLE
trying to worldmap travel triggers an assert

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#135]
the inhandler one in ~Control:
```
[Unknown]: Updated Area visibility: ar2000(visited, accessible and visible)                                         
[WorldMap]: CalculateDistances for Area: ar2000                                                                     
[ResourceManager]: Found 'WMDAG.bam' in 'chitin.key'.                                                               
[Unknown]: Gathering path information for: ar0700                                                                   
[Unknown]: Walkpath size is: 0                                                                                      
gemrb: gemrb/core/GUI/Control.cpp:58: virtual GemRB::Control::~Control(): Assertion `InHandler() == false' failed.                                                                                                

Thread 1 "gemrb" hit Breakpoint 1, 0x00007ffff6920c50 in abort () from /lib64/libc.so.6                             
(gdb) bt                                                                                                            
#0  0x00007ffff6920c50 in abort () from /lib64/libc.so.6                                                            
#1  0x00007ffff691810a in __assert_fail_base () from /lib64/libc.so.6                                               
#2  0x00007ffff6918182 in __assert_fail () from /lib64/libc.so.6                                                    
#3  0x00007ffff7b1a9c7 in GemRB::Control::~Control (this=<optimized out>, __in_chrg=<optimized out>)                
    at /home/kajak/dev/gemrb/gemrb/core/Holder.h:67                                                                 
#4  0x00007ffff7b3dbe9 in GemRB::WorldMapControl::~WorldMapControl (this=0x2a3fd30, __in_chrg=<optimized out>)      
    at /home/kajak/dev/gemrb/gemrb/core/GUI/WorldMapControl.cpp:84                                                  
#5  0x00007ffff37767f1 in GemRB_RemoveView (args=<optimized out>)                                                   
    at /home/kajak/dev/gemrb/gemrb/plugins/GUIScript/GUIScript.cpp:1946                                             
#6  0x00007ffff3412d0a in PyEval_EvalFrameEx () from /usr/lib64/libpython2.7.so.1.0
```

**Comment by bradallred** [comment]
should be fixed
