### ISSUE TITLE
Assertion `key.character == 0' failed

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#136]
Randomly mashing on the console to try to reproduce the null callback crash got me this:

```
TextContainer.cpp:870: virtual bool GemRB::TextContainer::OnKeyPress(const GemRB::KeyboardEvent&, short unsigned int): Assertion `key.character == 0' failed.                    

Thread 1 "gemrb" hit Breakpoint 1, 0x00007ffff6920c50 in abort () from /lib64/libc.so.6                             
(gdb) bt                                                                                                            
#0  0x00007ffff6920c50 in abort () from /lib64/libc.so.6
#1  0x00007ffff691810a in __assert_fail_base () from /lib64/libc.so.6
#2  0x00007ffff6918182 in __assert_fail () from /lib64/libc.so.6
#3  0x00007ffff7b3413a in GemRB::TextContainer::OnKeyPress(GemRB::KeyboardEvent const&, unsigned short) ()
    at /home/kajak/dev/gemrb/gemrb/core/GUI/TextSystem/TextContainer.cpp:870
#4  0x00007ffff7b189b6 in GemRB::Console::OnKeyPress(GemRB::KeyboardEvent const&, unsigned short) ()
    at /home/kajak/dev/gemrb/gemrb/core/GUI/Console.cpp:130
#5  0x00007ffff7b38725 in GemRB::Window::DispatchKey (event=..., keyView=<optimized out>, this=0x878eb0)
    at /home/kajak/dev/gemrb/gemrb/core/GUI/Window.cpp:311
#6  GemRB::Window::DispatchEvent (this=this@entry=0x878eb0, event=...)
    at /home/kajak/dev/gemrb/gemrb/core/GUI/Window.cpp:399
#7  0x00007ffff7b39c7c in GemRB::WindowManager::DispatchEvent (this=0x6963e0, event=...)
    at /home/kajak/dev/gemrb/gemrb/core/GUI/View.h:173
#8  0x00007ffff7b1c615 in GemRB::EventMgr::DispatchEvent(GemRB::Event&) ()
    at /usr/include/c++/8/bits/stl_tree.h:273
#9  0x00007fffedd2bace in GemRB::SDLVideoDriver::ProcessEvent(SDL_Event const&) ()
(gdb) p key
$1 = (const GemRB::KeyboardEvent &) @0x7fffffffd340: {<GemRB::EventBase> = {repeats = 1}, keycode = 102, 
  character = 170}

and
(gdb) p key
$3 = (const GemRB::KeyboardEvent &) @0x7fffffffd340: {<GemRB::EventBase> = {repeats = 1}, keycode = 53, 
  character = 53}
```
53 = "5", so the second one is more surprising.

**Comment by bradallred** [comment]
probably a modified key,  I simply removed the assert
