### ISSUE TITLE
cg: error when choosing to import char from char file

### ISSUE THREAD

**Issue by lynxlynxlynx** [bradallred/gemrb#99]
```
[Python/ERROR]: Traceback (most recent call last):
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 1841, in SelectionChanged
[Python/ERROR]:     UpdateActionsWindow ()
[Python/ERROR]:   File "../gemrb/GUIScripts/GUICommonWindows.py", line 664, in UpdateActionsWindow
[Python/ERROR]:     Button.SetFont ("NUMBER")
[Python/ERROR]: AttributeError: 'NoneType' object has no attribute 'SetFont'
```

**Comment by bradallred** [comment]
I think this was fixed in 0d253d7, I cant seem to reproduce this in BG2.

**Comment by bradallred** [comment]
I suppose the other games likely need the same fix tho

**Comment by bradallred** [comment]
BG1 & 2 and IWD checkout

PST doesn't seem to have this function and IWD2 is still untestable (tho im sure its broken; it'll get fixed when we fix the chargen there)
